"""create new tables

Revision ID: 2f310048e373
Revises: 
Create Date: 2026-05-19 17:37:11.062179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f310048e373'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('description', sa.String(length=1000), nullable=False))
    op.add_column('tasks', sa.Column('limit', sa.Date(), nullable=False))
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_column('tasks', 'limit')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'owner_id')
    # ### end Alembic commands ###
